### ISSUE TITLE
extension lz16 <-> lz12

### ISSUE THREAD

**Issue by tebe6502** [dmsc/lzss-sap#1]
file extensions should be the other way around  lz16 <-> lz12

\asm\playlzs12.asm

; Compress using:
;  lzss -b 12 -o 7 input.rsap test.lz16

\asm\playlzs16.asm

; Compress using:
;  lzss -b 16 -o 8 -m 1 input.rsap test.lz12

**Comment by dmsc** [comment]
Thank you, fixed!
