### ISSUE TITLE
chn_bits 8 bits for 9 channels?

### ISSUE THREAD

**Issue by ivop** [dmsc/lzss-sap#3]
Hi,

I noticed only 8 chn_bits are stored, but there are 9 possible streams.

Regards,
Ivo

**Comment by dmsc** [comment]
Hi!

Sorry for the late response.

> I noticed only 8 chn_bits are stored, but there are 9 possible streams.

Yes, the decoder assumes that the first channel (AUDF1) is always encoded, and the encoder warns if it detects that the first channel is empty. The assumption is that you always can reorder the channels to keep the first channel used.

Have Fun!

**Comment by ivop** [comment]
Thanks for the clarification.

Regards,
Ivo

**Comment by dmsc** [comment]
You are welcome :)

Closing now.
